version: '3.8'

services:
  web:
    build: ./
    command: >
      sh -c "python manage.py migrate --settings='corebackend.settings.staging' &&
            python manage.py runserver 0.0.0.0:8000 --settings='corebackend.settings.staging'"

    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=psql
      - POSTGRES_PASSWORD=psql
      - POSTGRES_DB=urlshorterdb
    ports:
      - 5432:5432

volumes:
  postgres_data:
