# Generated by Django 2.0.6 on 2023-11-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shorter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShorter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_original', models.URLField()),
                ('code_shorter', models.CharField(max_length=10, null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Url shorter',
                'verbose_name_plural': "Url's shorter",
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
